[General]
network = Network

*.n = 4
*.host[0].app[0].thinkTime = 0s

*.visualizer.interfaceTableVisualizer.displayInterfaceTables = true
*.visualizer.interfaceTableVisualizer.format = "%N: %m %a"
*.visualizer.interfaceTableVisualizer.nodeFilter = "not(switch*)"
*.visualizer.interfaceTableVisualizer.displayBackground = true
*.visualizer.interfaceTableVisualizer.placementHint = "right"
*.visualizer.interfaceTableVisualizer.displayWiredInterfacesAtConnections = false

*.host[*].numPcapRecorders = 1
**.pcapRecorder[*].pcapFile = "results/" + fullPath() + ".pcap"
**.pcapRecorder[*].alwaysFlush = true
**.crcMode = "computed"
**.fcsMode = "computed"


#Numero de hosts
*.host[*].typename = "StandardHost"
*.host[0].numApps = 1
*.host[1..3].numApps = 0
*.server_local.numApps = 1
*.server_remote.numApps = 1

#Configuracion servidor local
*.server_local.app[0].typename = "TcpGenericServerApp" 
*.server_local.app[0].port = 80

#Configuracion servidor remoto
*.server_remote.app[0].typename = "TcpGenericServerApp" 
*.server_remote.app[0].port = 80

#Configuracion host0
*.host[0].app[0].typename = "TcpBasicClientApp" 
*.host[0].app[0].connectAddress = "server_remote"
#*.host[0].app[0].connectAddress = "server_local" 
*.host[0].app[0].startTime = 6s
*.host[0].app[0].tOpen = 0s
*.host[0].app[0].tSend = 6s
*.host[0].app[0].tClose = 50s
*.host[0].app[0].replyLength = 1000B
*.host[0].app[0].idleInterval = 4s

[Config IPv4]
extends = General

**.hasIpv6 = false
**.hasIpv4 = true

*.configurator.config = xmldoc("config.xml")


# Servidores DHCP
*.server_local.numApps = 2
*.server_local.app[1].typename = "DhcpServer"
*.server_local.app[1].interface = "eth0"
*.server_local.app[1].gateway = "192.168.0.1"
*.server_local.app[1].numReservedAddresses = 10
*.server_local.app[1].maxNumClients = 5
*.server_local.app[1].leaseTime = 300s 

*.router.hasDhcp = true
*.router.dhcp.interface = "eth0"
*.router.dhcp.numReservedAddresses = 5
*.router.dhcp.maxNumClients = 5
*.router.dhcp.leaseTime = 300s

*.host[0].numApps = 2
*.host[1..3].numApps = 1
*.host[0].app[1].typename = "DhcpClient"
*.host[1..3].app[0].typename = "DhcpClient"
*.host[3].app[0].startTime = 0.05s
*.host[0].app[1].startTime = 0.1s
*.host[1..2].app[0].startTime = 0.2s



[Config IPv6]

extends = General

**.hasIpv6 = true
**.hasIpv4 = false

# MACs Requeridas
*.host[0].eth[0].address = "04:00:00:AA:BB:C0"
*.host[1].eth[0].address = "04:00:00:CC:DD:E1"
*.host[2].eth[0].address = "04:00:00:FF:00:F2"
*.host[3].eth[0].address = "04:00:00:01:02:03"

*.server_remote.eth[0].address = "04:00:00:00:00:02"
*.server_local.eth[0].address = "04:00:00:00:00:01"


# Aplicación TCP del Cliente (host[0])
*.host[0].numApps = 1
*.host[1..3].numApps = 0

