[General]
network = Manet


num-rngs = 2
**.mobility.rng-0 = 1

seed-0-mt = 0
seed-1-mt = 7117
#seed-1-mt = 71177                       #Para el apartado 3 - AODV
#seed-1-mt = 777                         #Para el apartado 3 - dsdv
#seed-1-mt = 7117 + ${repetition}        #Para el apartado 4 - gráficas

**.arp.typename = "GlobalArp"

*.configurator.config = xmldoc("config.xml")

**.radio.displayCommunicationRange = true
*.visualizer.networkRouteVisualizer.displayRoutes = true
*.visualizer.networkRouteVisualizer.packetFilter = "UdpBasicAppData*"
*.visualizer.interfaceTableVisualizer.displayInterfaceTables = true
*.visualizer.interfaceTableVisualizer.interfaceFilter = "wlan*"

*.mobile[*].mobility.typename = "RandomWaypointMobility"
*.mobile[*].mobility.speed = 12mps
*.mobile[*].mobility.waitTime = 2s
*.mobile[*].mobility.initFromDisplayString = false
*.mobile[*].mobility.constraintAreaMinX = 200m
*.mobile[*].mobility.constraintAreaMaxX = 1200m
*.mobile[*].mobility.constraintAreaMinY = 50m
*.mobile[*].mobility.constraintAreaMaxY = 450m
*.mobile[*].mobility.constraintAreaMinZ = 0m
*.mobile[*].mobility.constraintAreaMaxZ = 0m

# Aplicación emisora en static1
*.static1.numApps = 1
*.static1.app[0].typename = "UdpBasicApp"
*.static1.app[0].destAddresses = "static2"
*.static1.app[0].messageLength = 100B
*.static1.app[0].sendInterval = 30ms
*.static1.app[0].startTime = 10s
*.static1.app[0].destPort = 1000


# Aplicación receptora/respuesta en static2
*.static2.numApps = 1
*.static2.app[0].typename = "UdpEchoApp"
*.static2.app[0].localPort = 1000

*.n=16

**.radio.transmitter.power = 2.2mW
#**.radio.transmitter.power = ${power=0.5..4 step 0.5}mW

#**.hasStatus = true
#*.scenario.script = xml("<scenario><at t='15'>\
#<shutdown module='mobile[6]'/></at></scenario>")


# Apartado gráficas
#repeat = 11
#sim-time-limit = 300s
#config-recording = none
#**.param-recording = false
#**.vector-recording = false
#**.bin-recording = false
# Solo activamos estadísticas para las aplicaciones de los nodos estáticos
#*.static*.app[0].statistic-recording = true


[Config AODV]
**.routingApp.typename = "Aodv"


[Config DSDV]
**.routing.typename = "Dsdv"
**.helloInterval = 3s