[general]
;autofallthrough=yes

[demo]
exten => 101,1,Dial(Pjsip/sip1)
exten => sip1,1,Dial(Pjsip/sip1)

exten => 102,1,Dial(Pjsip/sip2,10,m)
exten => sip2,1,Dial(Pjsip/sip2,10,m)

exten => 200,1,Answer()
same => n,Wait(2)
same => n,Background(hello-world)
same => n,Wait(1)
same => n,Background(enter-ext-of-person)
same => n,WaitExten(10)
same => n,Hangup()

exten => 300,1,Answer()
exten => 300,2,Echo()
exten => 300,3,Hangup()

