[general]
format=wav49|wav
serveremail=voicemail@udc.test.es
attach=yes
maxsilence=10
maxlogins=3

[zonemessages]
european=Europe/Copenhagen|'vm-received' a d b 'digits/at' HM

[sm]
001=1234,Ismael,ismael.brea@udc.es,,
002=5678,Ismael,ismael.brea@udc.es,,
